#!/usr/bin/env bash

set -e

# ======= Bootstrap =======
sudo apt-get update
sudo apt-get upgrade -y

sudo apt install git
#git config --global user.name "JD Solanki"
#git config --global user.email "jdsolanki0001@gmail.com"
# / ==== Bootstrap

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" -d "$BASEDIR" -c "$config" $ARGS
}

run_dotbot 'steps/startup.yml' || true
run_dotbot 'steps/applications.yml' || true

cat post-config-notes.txt